TrainingArguments:
  num_train_epochs: 5
  warmup_steps: 1000
  per_device_train_batch_size: 8
  weight_decay: 0.01
  logging_steps: 10
  evaluation_strategy: steps
  eval_steps: 500
  save_steps: 1e6
  gradient_accumulation_steps: 8



